### ISSUE TITLE
request to support groovy 2.4.4

### ISSUE THREAD

**Issue by dirkm** [bazhenov/groovy-shell-server#18]
We pull in through spring-boot groovy 2.4.4 in our jar.

groovy-shell-server does not start when 2.4.4 is present. The error is:

$ ssh localhost -p 6789
Unable to load default scripts: java.lang.NullPointerException: null

We can probably downgrade to groovy 2.2, but would prefer if the groovy-shell-service upgraded instead.

**Comment by bazhenov** [comment]
1.7.1 will hit Maven Central in several hours. By the way if several version of the same dependency are specified, the one closer to project root will be chosen. So you always can reload dependency version in your `pom.xml`.
