### ISSUE TITLE
ssh-dss has been deprecated in OpenSSH 7.2

### ISSUE THREAD

**Issue by kshchepanovskyi** [bazhenov/groovy-shell-server#22]
`ssh-dss` has been deprecated in OpenSSH 7.2.

When I run following command for a latest release (1.7.1) of groovy-shell-server, it returns an error:

```
$ ssh localhost -p 6789
Unable to negotiate with 127.0.0.1 port 6789: no matching host key type found. Their offer: ssh-dss
```

It can be fixed by upgrading `sshd-core` to 1.4.0:

```xml
<dependency>
    <groupId>org.apache.sshd</groupId>
    <artifactId>sshd-core</artifactId>
    <version>1.4.0</version>
</dependency>
```

Can you please make a fix and deploy new version to maven-central?

**Comment by bazhenov** [comment]
Changes are deployed as a version 1.7.2. Typically it takes several hours to hit maven central.

**Comment by kshchepanovskyi** [comment]
Thanks!
